/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Quin.sm
 */

package quindonc;


public class QuinContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public QuinContext(Quin owner)
    {
        this (owner, MainMap.Start);
    }

    public QuinContext(Quin owner, QuinState initState)
    {
        super (initState);

        _owner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
        return;
    }

    public void bad()
    {
        _transition = "bad";
        getState().bad(this);
        _transition = "";
        return;
    }

    public void dial()
    {
        _transition = "dial";
        getState().dial(this);
        _transition = "";
        return;
    }

    public void eighteen()
    {
        _transition = "eighteen";
        getState().eighteen(this);
        _transition = "";
        return;
    }

    public void end1()
    {
        _transition = "end1";
        getState().end1(this);
        _transition = "";
        return;
    }

    public void end10()
    {
        _transition = "end10";
        getState().end10(this);
        _transition = "";
        return;
    }

    public void end11()
    {
        _transition = "end11";
        getState().end11(this);
        _transition = "";
        return;
    }

    public void end2()
    {
        _transition = "end2";
        getState().end2(this);
        _transition = "";
        return;
    }

    public void end3()
    {
        _transition = "end3";
        getState().end3(this);
        _transition = "";
        return;
    }

    public void end4()
    {
        _transition = "end4";
        getState().end4(this);
        _transition = "";
        return;
    }

    public void end5()
    {
        _transition = "end5";
        getState().end5(this);
        _transition = "";
        return;
    }

    public void end6()
    {
        _transition = "end6";
        getState().end6(this);
        _transition = "";
        return;
    }

    public void end7()
    {
        _transition = "end7";
        getState().end7(this);
        _transition = "";
        return;
    }

    public void end8()
    {
        _transition = "end8";
        getState().end8(this);
        _transition = "";
        return;
    }

    public void end9()
    {
        _transition = "end9";
        getState().end9(this);
        _transition = "";
        return;
    }

    public void num1()
    {
        _transition = "num1";
        getState().num1(this);
        _transition = "";
        return;
    }

    public void num2()
    {
        _transition = "num2";
        getState().num2(this);
        _transition = "";
        return;
    }

    public void one()
    {
        _transition = "one";
        getState().one(this);
        _transition = "";
        return;
    }

    public void star()
    {
        _transition = "star";
        getState().star(this);
        _transition = "";
        return;
    }

    public void two()
    {
        _transition = "two";
        getState().two(this);
        _transition = "";
        return;
    }

    public void wait1()
    {
        _transition = "wait1";
        getState().wait1(this);
        _transition = "";
        return;
    }

    public QuinState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((QuinState) _state);
    }

    protected Quin getOwner()
    {
        return (_owner);
    }

    public void setOwner(Quin owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private Quin _owner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class QuinState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected QuinState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(QuinContext context) {}
        protected void exit(QuinContext context) {}

        protected void bad(QuinContext context)
        {
            Default(context);
        }

        protected void dial(QuinContext context)
        {
            Default(context);
        }

        protected void eighteen(QuinContext context)
        {
            Default(context);
        }

        protected void end1(QuinContext context)
        {
            Default(context);
        }

        protected void end10(QuinContext context)
        {
            Default(context);
        }

        protected void end11(QuinContext context)
        {
            Default(context);
        }

        protected void end2(QuinContext context)
        {
            Default(context);
        }

        protected void end3(QuinContext context)
        {
            Default(context);
        }

        protected void end4(QuinContext context)
        {
            Default(context);
        }

        protected void end5(QuinContext context)
        {
            Default(context);
        }

        protected void end6(QuinContext context)
        {
            Default(context);
        }

        protected void end7(QuinContext context)
        {
            Default(context);
        }

        protected void end8(QuinContext context)
        {
            Default(context);
        }

        protected void end9(QuinContext context)
        {
            Default(context);
        }

        protected void num1(QuinContext context)
        {
            Default(context);
        }

        protected void num2(QuinContext context)
        {
            Default(context);
        }

        protected void one(QuinContext context)
        {
            Default(context);
        }

        protected void star(QuinContext context)
        {
            Default(context);
        }

        protected void two(QuinContext context)
        {
            Default(context);
        }

        protected void wait1(QuinContext context)
        {
            Default(context);
        }

        protected void Default(QuinContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
    // Constants.
    //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class MainMap
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final MainMap_Start Start =
            new MainMap_Start("MainMap.Start", 0);
        public static final MainMap_Star1 Star1 =
            new MainMap_Star1("MainMap.Star1", 1);
        public static final MainMap_Star2 Star2 =
            new MainMap_Star2("MainMap.Star2", 2);
        public static final MainMap_Star3 Star3 =
            new MainMap_Star3("MainMap.Star3", 3);
        public static final MainMap_Enter1 Enter1 =
            new MainMap_Enter1("MainMap.Enter1", 4);
        public static final MainMap_Enter2 Enter2 =
            new MainMap_Enter2("MainMap.Enter2", 5);
        public static final MainMap_Enter3 Enter3 =
            new MainMap_Enter3("MainMap.Enter3", 6);
        public static final MainMap_Emerg Emerg =
            new MainMap_Emerg("MainMap.Emerg", 7);
        public static final MainMap_Info1 Info1 =
            new MainMap_Info1("MainMap.Info1", 8);
        public static final MainMap_Info2 Info2 =
            new MainMap_Info2("MainMap.Info2", 9);
        public static final MainMap_Info3 Info3 =
            new MainMap_Info3("MainMap.Info3", 10);
        public static final MainMap_Final Final =
            new MainMap_Final("MainMap.Final", 11);
    }

    protected static class MainMap_Default
        extends QuinState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected MainMap_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Start
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void dial(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Star1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void end1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Star1
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Star1(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end2(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Star2);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Star2
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Star2(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end3(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Star3);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Star3
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Star3(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end4(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Enter1
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Enter1(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void bad(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void eighteen(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Emerg);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void end5(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void num1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void num2(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter2);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Enter2
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Enter2(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void bad(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void eighteen(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Emerg);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void end6(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void num1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void num2(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter3);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Enter3
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Enter3(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void bad(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void eighteen(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Emerg);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void end7(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void num1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void num2(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Emerg
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Emerg(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end8(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Info1
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Info1(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end9(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void one(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void two(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info2);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Info2
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Info2(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end10(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void one(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void two(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info3);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Info3
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Info3(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void end11(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Final);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void one(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void star(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Enter1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void two(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Info1);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void wait1(QuinContext context)
        {

            (context.getState()).exit(context);
            context.setState(MainMap.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Final
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Final(String name, int id)
        {
            super (name, id);
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
